### ISSUE TITLE
Use th class (sorting-asc or sorting-desc) to define sorting

### ISSUE THREAD

**Issue by palmerlovett** [joequery/Stupid-Table-Plugin#114]
It would be useful if the th class defined the sorting in order.

It would then be easy to specify a default sorted column no matter what the content in the table is (useful really when dealing with php generated tables from a database, we wouldn't have to rely on the query)

Also useful when using dynamic content that loads every time you edit it. If it were defined by class, it would be easy to persist that class after a page reload, or reloading the dynamic content.

**Comment by joequery** [comment]
I believe this is solved by #185 . Please reopen if not. Thanks!
