### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by paazmaya** [joequery/Stupid-Table-Plugin#116]
Would it be possible to add versioning, via tags and a change log, in order to keep track of what has happened and also easier matching via Bower for example?

Current version could start from 1.0.0 as it is pretty mature and tested.

**Comment by realtebo** [comment]
I noticed that finally whe have semver tags. Thanks (and I think that this issue could be closed)

**Comment by joequery** [comment]
Good idea. I think I'm going to close a few issues related to this whenever I update the docs!

**Comment by joequery** [comment]
Semver, tags, and changelog have been implemented. Thanks for the issue!
