### ISSUE TITLE
Sort bt default

### ISSUE THREAD

**Issue by waister** [joequery/Stupid-Table-Plugin#126]
Sort with "data-sort-default" is not working.

**Comment by ticktoo** [comment]
+1

**Comment by yairEO** [comment]
issue title is misleading. it should be `setting default sort direction attribute has no effect`

**Comment by joequery** [comment]
The default direction of the sort occurs. The attribute does not indicate that the table will initiate sorting upon page load. Whether that should be its own option would be a separate issue.

**Comment by yairEO** [comment]
@joequery - yes, I addressed this in https://github.com/joequery/Stupid-Table-Plugin/issues/180

**Comment by joequery** [comment]
This was implemented in #185 . thanks for the issue!
