### ISSUE TITLE
npm/Bower packages

### ISSUE THREAD

**Issue by idleberg** [joequery/Stupid-Table-Plugin#131]
It helped a lot that you made Stupid Table available through cdnjs and I think many people would equally appreciate if you could make it available through npm and/or bower. For starters a simple `package.json` would do, since then one could perform a simple `npm install joequery/Stupid-Table-Plugin`.

**Comment by kenmoini** [comment]
This pull request and a set of console commands would set it up in bower :smile: https://github.com/joequery/Stupid-Table-Plugin/pull/133

**Comment by joequery** [comment]
Bower support is finally added! Thanks for the issues everyone :)
