### ISSUE TITLE
I am having trouble installing the code

### ISSUE THREAD

**Issue by kevinm20** [joequery/Stupid-Table-Plugin#135]
This is how my tags look like:

        <script src="http://code.jquery.com/jquery-1.11.2.js"></script>
        <script src="jquery.stupidtable.js"></script>
	<script src="jquery.stupidtable.min.js"></script>

of course it is inside the <head>, btw

This is my first time installing a jQuery plugin, so can someone tell me how to do it/what is wrong?

**Comment by svivian** [comment]
You are including Stupid Table twice. The two JS files are the same plugin but the `.min.js` one is [minified](http://en.wikipedia.org/wiki/Minification_\(programming\)). Remove the middle line from your example code.
