### ISSUE TITLE
How do I sort money?

### ISSUE THREAD

**Issue by golevel** [joequery/Stupid-Table-Plugin#143]
I get completely random looking sorting when I sort $x by int or float. My column is in whole dollars.

**Comment by joequery** [comment]
Can you post your table?

**Comment by golevel** [comment]
I solved it by adding data-sort-value="x" and sorted by int instead of worrying about how to factor in the $ and formatting.

**Comment by joequery** [comment]
That is exactly what I would have recommended. :+1:
