### ISSUE TITLE
what is string-ins?

### ISSUE THREAD

**Issue by LukeXF** [joequery/Stupid-Table-Plugin#153]
I understand int, float and string but string-ins in the documentation is unknown to me? Does it have a purpose or is it a spelling mistake maybe?

`string-ins (case-insensitive)`

**Comment by joequery** [comment]
Hello!

```
x = ["A", "b", "C", "d", "E"]
x.sort()
>>> ["A", "C", "E", "b", "d"]
x = ["a", "b", "c", "d", "e"]
x.sort()
>>> ["a", "b", "c", "d", "e"]
```

Try it in a JS console

**Comment by LukeXF** [comment]
Ah okay, so it's if you want the strings to be alphabetical regardless of case sensitivity.

**Comment by LukeXF** [comment]
You probably should explain that a bit better in the documentation.

**Comment by joequery** [comment]
Most developers know what case insensitive string sorting is. And now you do :)

**Comment by joequery** [comment]
Also, [case insensitive sort](https://www.google.com/search?q=case+insensitive+sort)
