### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by Anahkiasen** [joequery/Stupid-Table-Plugin#154]
Would be great to have this available on NPM for people using Webpack, Browserify etc or just using NPM as their main front-end package manager.

**Comment by joequery** [comment]
Alrighty, sounds good! Thanks for the issue.

**Comment by johannesnagl** [comment]
+1!

**Comment by paazmaya** [comment]
:+1:

**Comment by johannesnagl** [comment]
It's still our only package which is not managed by npm's package.json :/

**Comment by joequery** [comment]
Alrighty. Here we go - https://www.npmjs.com/package/stupid-table-plugin. Thanks for the reminders everyone.

**Comment by johannesnagl** [comment]
thanks! works for me, @joequery - but I don't think, that the library should have a dependency on `npm`.

**Comment by joequery** [comment]
Hm. `npm init` autogenerated that.
