### ISSUE TITLE
Error with GitHub Pages page

### ISSUE THREAD

**Issue by PhantomWatson** [joequery/Stupid-Table-Plugin#159]
jQuery is not being loaded on https://joequery.github.io/Stupid-Table-Plugin/, which is preventing any of the demos from working.

**Comment by svivian** [comment]
It appears to be due to jQuery trying to load over HTTP when the page is HTTPS. Visiting http://joequery.github.io/Stupid-Table-Plugin/ works.

**Comment by PhantomWatson** [comment]
Visiting http://joequery.github.io/Stupid-Table-Plugin/ automatically redirects to the https:// version, at least for me.

**Comment by svivian** [comment]
Strange, that doesn't happen for me.

Anyway I've just updated it to use protocol-relative links so it should all be working fine :)

**Comment by joequery** [comment]
Thanks for the issue @PhantomWatson and thanks for cleaning it up @svivian :)

**Comment by PhantomWatson** [comment]
And thanks to you and the other contributors for your work on this project.
