### ISSUE TITLE
Sorting on metadata values rather than the actual TD content

### ISSUE THREAD

**Issue by nltesown** [joequery/Stupid-Table-Plugin#164]
Here's my current situation: I have a table row where I display in each cell a numeric value represented as a graphical "bar" (bar chart-like) - a div with a variable width. I should be able to make this row sortable data based on the numeric value in a data- attribute : `<td data-value="86">...</td>`, not the actual content of the `td` element. It would be a useful feature for this "stupid" plugin to take this use case into account (granted, my example may not be the most frequent).

**Comment by joequery** [comment]
https://github.com/joequery/Stupid-Table-Plugin#data-with-multiple-representationspredefined-order
