### ISSUE TITLE
"Locking" bottom row from sorting?

### ISSUE THREAD

**Issue by PullJosh** [joequery/Stupid-Table-Plugin#165]
I have a table in which the bottom row contains the sum of each of the columns, and I'd like to keep it at the bottom even after sorting the table. Is this possible?

_(Thanks for the great plugin, btw!)_

**Comment by svivian** [comment]
Sounds like the same issue discussed in #149.

**Comment by 4meFirst** [comment]
Why don't you put the row inside tfoot tag?

**Comment by PullJosh** [comment]
> Why don't you put the row in tfoot tag?  

I didn't know that tag existed! Thanks for the help; it's working great now! :D
