### ISSUE TITLE
wrong bower main file

### ISSUE THREAD

**Issue by alexsakhnov** [joequery/Stupid-Table-Plugin#168]
main file should be `stupidtable.js`, not `stupidtable.min.js`

`bower install` ouput:
`bower jquery-stupid-table#*     invalid-meta The "main" field cannot contain minified files`

**Comment by joequery** [comment]
Thanks for the issue. Do you know where minified files should be specified?

**Comment by alexsakhnov** [comment]
As far as I know, nowhere. The official specification: https://github.com/bower/spec/blob/master/json.md

**Comment by joequery** [comment]
If you'd like to make a PR for it feel free :)
