### ISSUE TITLE
Can't sort multiple float columns. Only 1 works

### ISSUE THREAD

**Issue by MyWek** [joequery/Stupid-Table-Plugin#179]
I have a very simple usage of stupidtable, there are no embedded tables or anything fancy.  Just a table with around 8 columns, most set for string sorting, but 2 columns set to float sorting.  Only one of the columns sort by floats, the other columns seems to be sorting by some unknown criteria.

As another test I made another of the columns sortable by float, and then 2 columns sorted by float, but one column did not. Everything else works fine.

I don't have time to create and upload demos etc, just bringing this to your attention. I'll check back in the future to see if there's  afix, and will hope my customer doesn't notice the sorting problem in the meantime, because I do like the simplicity of this plugin.

**Comment by joequery** [comment]
I could not replicate this issue. I was able to make a table with multiple float columns sort correctly. Without a test case, I will have to close this issue.
