### ISSUE TITLE
Sort IP Address

### ISSUE THREAD

**Issue by shw1395** [joequery/Stupid-Table-Plugin#195]
Here has very useful code for reference: https://github.com/DataTables/Plugins/blob/master/sorting/ip-address.js , copy them into "$(function(){ var ip_address_pre = function(a) { ...return x;},"

then add this after "var table = $("table[id^='Stupid-Table-Plugin'][class^='table-striped']").stupidtable({"
          "date": function(a,b) {
            // Get these into date objects for comparison.
            ...
          },
           "ip": function(a,b) {
            aIP = ip_address_pre(a);
            bIP = ip_address_pre(b);
            return aIP - bIP;
          }
        });

 testing result and good luck!

**Comment by joequery** [comment]
Cool, thanks for the example. :+1:
