### ISSUE TITLE
Incorrect sorting of columns containing word+number, and numbers containing spaces.

### ISSUE THREAD

**Issue by thejustsoul** [joequery/Stupid-Table-Plugin#199]
Hello, how to fix this wrong sorting?
Example: https://jsfiddle.net/cjwwxmbg/

**Comment by joequery** [comment]
Hey there!

This should get you started: https://jsfiddle.net/quw3q0y1/

**Comment by thejustsoul** [comment]
Wow, excellent -) I understand that you need to write the processing of such data types (magic)? Is it possible to add this to the main code so that people who come across it can use this sort of "out of the box"?

**Comment by joequery** [comment]
I would prefer not to. This isn't really an "out of the box" plugin, which is why it's able to be so small.

You can find a bunch of useful sorting functions in the DataTables repo: https://github.com/DataTables/Plugins/tree/master/sorting
