### ISSUE TITLE
TypeError: $table.on is not a function

### ISSUE THREAD

**Issue by dkean** [joequery/Stupid-Table-Plugin#98]
Love this column sorter, but I seem to be stuck on some error i FireBug, which I do not know how to debug...

TypeError: $table.on is not a function
$table.on("click.stupidtable", "th", function() {

**Comment by LukeXF** [comment]
I'm running jQuery v1.11.3 and this is still an issue for me, any suggestions?

**Comment by joequery** [comment]
@LukeXF Can you make a fiddle reproducing? Thanks!

**Comment by LukeXF** [comment]
Issue resolved, had jQuery v1.11.3 running and for some reason another JS file was including jQuery v1.2.6 aaaall the way back from 2008. Thanks for the quick response.

**Comment by joequery** [comment]
Hahah, it's like a time machine in a `<script>` tag! ;)
